# Generated by Django 6.0.3 on 2026-09-30 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_options_school_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='school/teachers/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPhotoEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_embeddings', to='school.teacher')),
                ('teacher_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='school.teacherphoto')),
            ],
        ),
    ]
