# Generated by Django 6.0.3 on 2026-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('teagarden_head', 'Tea Garden Head'), ('super_attendant', 'Super Attendant'), ('attendant', 'Attendant'), ('doctor', 'Doctor'), ('head_nurse', 'Head Nurse'), ('nurse', 'Nurse')], max_length=20),
        ),
    ]
