# Generated by Django 6.0.3 on 2026-04-02 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecheattendant',
            name='role',
            field=models.CharField(choices=[('super_attendant', 'Super Attendant'), ('attendant', 'Attendant')], default='attendent', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crecheattendant',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crecheattendant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('teagarden_head', 'Tea Garden Head'), ('staff', 'Staff')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='crecheattendant',
            unique_together={('creche', 'user')},
        ),
    ]
