# Generated by Django 6.0.3 on 2026-04-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0003_crecheattendant_role_alter_crecheattendant_mobile_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_date', models.DateField()),
                ('meal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation_photo', models.ImageField(blank=True, null=True, upload_to='food/preparation/')),
                ('distribution_photo', models.ImageField(blank=True, null=True, upload_to='food/distribution/')),
                ('ambience_photo', models.ImageField(blank=True, null=True, upload_to='food/ambience/')),
                ('food_description', models.TextField(blank=True, null=True)),
                ('estimated_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_fibre_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='creches.creche')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creches.crecheattendant')),
            ],
        ),
        migrations.CreateModel(
            name='ChildGrowthMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='creches.child')),
            ],
            options={
                'unique_together': {('child', 'measured_on')},
            },
        ),
    ]
