# Generated by Django 6.0.3 on 2026-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0004_foodmonitoring_childgrowthmonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecheattendant',
            name='attendant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
