# Generated by Django 6.0.3 on 2026-04-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0005_crecheattendant_attendant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecheattendant',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
