# Generated by Django 6.0.4 on 2026-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0006_crecheattendant_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
