# Generated by Django 4.2.16 on 2026-05-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0009_alter_attendantattendance_id_alter_child_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrecheAttendantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='attendants/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='creches.crecheattendant')),
            ],
            options={
                'verbose_name': 'Creche Attendant Photo',
                'verbose_name_plural': 'Creche Attendant Photos',
            },
        ),
        migrations.CreateModel(
            name='CrecheAttendantPhotoEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_embeddings', to='creches.crecheattendant')),
                ('attendant_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='creches.crecheattendantphoto')),
            ],
            options={
                'verbose_name': 'Creche Attendant Photo Embedding',
                'verbose_name_plural': 'Creche Attendant Photo Embeddings',
            },
        ),
    ]
