# Generated by Django 6.0.4 on 2026-05-26 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0009_childphotoembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_items', models.JSONField(default=list, help_text='Array of food items')),
                ('food_update_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_records', to='creches.crecheattendant')),
                ('creche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_records', to='creches.creche')),
            ],
            options={
                'verbose_name': 'Food Record',
                'verbose_name_plural': 'Food Records',
                'ordering': ['-food_update_date'],
            },
        ),
    ]
