# Generated by Django 4.2.16 on 2026-06-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0010_crecheattendantphoto_crecheattendantphotoembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_items', models.JSONField(default=list, help_text='Array of food items')),
                ('food_time', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, null=True)),
                ('food_update_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_records', to='creches.crecheattendant')),
                ('creche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_records', to='creches.creche')),
            ],
            options={
                'verbose_name': 'Food Record',
                'verbose_name_plural': 'Food Records',
                'ordering': ['-food_update_date'],
            },
        ),
    ]
