# Generated by Django 4.2.16 on 2026-06-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0011_foodrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='food_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
