# Generated by Django 6.0.4 on 2026-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0012_crecheattendantphotoembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecord',
            name='food_time',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]