# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0013_foodrecord_add_food_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='food_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]