# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0014_alter_foodrecord_food_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecordAttendent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_items', models.JSONField(default=list, help_text='Array of food items')),
                ('food_time', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, null=True)),
                ('food_update_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_record_attendents', to='creches.crecheattendant')),
                ('creche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_record_attendents', to='creches.creche')),
            ],
            options={
                'verbose_name': 'Food Record Attendent',
                'verbose_name_plural': 'Food Record Attendents',
                'ordering': ['-food_update_date'],
            },
        ),
    ]