# Generated by Django 6.0.3 on 2026-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0015_foodrecordattendent'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecordattendent',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for food record', null=True),
        ),
    ]
