# Generated by Django 6.0.3 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0016_foodrecordattendent_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='childgrowthmonitoring',
            name='weight_pic',
            field=models.ImageField(blank=True, null=True, upload_to='child_growth/'),
        ),
        migrations.AddField(
            model_name='childgrowthmonitoring',
            name='height_pic',
            field=models.ImageField(blank=True, null=True, upload_to='child_growth/'),
        ),
    ]