# Generated by Django 6.0.3 on 2026-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creches', '0016_foodrecordattendent_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('teagarden_head', 'Tea Garden Head'), ('staff', 'Staff'), ('teacher', 'Teacher')], max_length=20),
        ),
    ]
