# Generated by Django 6.0.3 on 2026-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0002_alter_doctor_user_alter_nurse_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='role',
            field=models.CharField(choices=[('head_nurse', 'Head Nurse'), ('nurse', 'Nurse')], default='nurse', max_length=30),
        ),
    ]
