# Generated by Django 6.0.3 on 2026-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0003_alter_nurse_mobile_no_alter_nurse_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
