# Generated by Django 6.0.3 on 2026-04-03 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0004_alter_nurse_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, unique=True)),
                ('medicine_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit_name', models.CharField(default='Unit', max_length=50)),
                ('min_stock_level', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('transaction_at', models.DateTimeField(auto_now_add=True)),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='healthcenter.healthcenter')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('treatment_date', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='healthcenter.healthcenter')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTreatmentMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_qty', models.IntegerField(default=0)),
                ('issued_qty', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.medicine')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='healthcenter.patienttreatment')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMedicineRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_week_start', models.DateField()),
                ('requisition_week_end', models.DateField()),
                ('requisition_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='SUBMITTED', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='healthcenter.healthcenter')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMedicineRequisitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_stock_qty', models.IntegerField(default=0)),
                ('requested_qty', models.IntegerField(default=0)),
                ('auto_low_stock_flag', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.medicine')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='healthcenter.weeklymedicinerequisition')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='doctor_checkin/')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_geo_verified', models.BooleanField(default=False)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_photo', models.ImageField(blank=True, null=True, upload_to='doctor_exit/')),
                ('exit_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('exit_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('exit_geo_verified', models.BooleanField(default=False)),
                ('nurse_present', models.BooleanField(default=False)),
                ('hygiene_maintained', models.BooleanField(default=False)),
                ('patients_visited_today', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='healthcenter.doctor')),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_attendances', to='healthcenter.healthcenter')),
            ],
            options={
                'unique_together': {('doctor', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='HealthCenterMedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock_qty', models.IntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_stocks', to='healthcenter.healthcenter')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcenter.medicine')),
            ],
            options={
                'unique_together': {('health_center', 'medicine')},
            },
        ),
        migrations.CreateModel(
            name='NurseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('attendance_photo', models.ImageField(blank=True, null=True, upload_to='nurse_attendance/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geo_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_attendances', to='healthcenter.healthcenter')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='healthcenter.nurse')),
            ],
            options={
                'unique_together': {('nurse', 'attendance_date')},
            },
        ),
    ]
