# Generated by Django 6.0.3 on 2026-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0005_medicine_medicinestocktransaction_patienttreatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
