# Generated by Django 6.0.4 on 2026-04-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0006_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
