# Generated by Django 6.0.4 on 2026-04-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0007_doctor_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='nurse_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
