# Generated by Django 6.0.4 on 2026-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0008_nurse_face_encoding_nurse_nurse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatments/'),
        ),
    ]
