# Generated by Django 6.0.4 on 2026-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0009_patienttreatment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed'), (3, 'Cancelled')], default=0),
        ),
    ]
