# Generated by Django 4.2.16 on 2026-05-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0010_patienttreatment_image_patienttreatment_status_and_more'),
        ('healthcenter', '0014_nursephotoembedding'),
    ]

    operations = [
    ]
