# Generated by Django 4.2.16 on 2026-05-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0015_merge_20260527_0552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorphotoembedding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorphotoembedding',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorphotoembedding',
            name='doctor_photo',
        ),
        migrations.DeleteModel(
            name='DoctorPhoto',
        ),
        migrations.DeleteModel(
            name='DoctorPhotoEmbedding',
        ),
    ]
