# Generated by Django 6.0.4 on 2026-05-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0015_doctorcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcheckin',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorcheckin',
            name='checkout_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorcheckin',
            name='hygiene_maintained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorcheckin',
            name='nurse_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorcheckin',
            name='patients_visited_today',
            field=models.IntegerField(default=0),
        ),
    ]
