# Generated by Django 4.2.16 on 2026-05-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0016_alter_doctorphotoembedding_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='doctors/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='healthcenter.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Photo',
                'verbose_name_plural': 'Doctor Photos',
            },
        ),
        migrations.CreateModel(
            name='DoctorPhotoEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_embeddings', to='healthcenter.doctor')),
                ('doctor_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='healthcenter.doctorphoto')),
            ],
            options={
                'verbose_name': 'Doctor Photo Embedding',
                'verbose_name_plural': 'Doctor Photo Embeddings',
                'unique_together': {('doctor',)},
            },
        ),
    ]
