# Generated by Django 4.2.16 on 2026-05-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0017_doctorphoto_doctorphotoembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='doctor_checkin_photos/')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_geo_verified', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(default=0.0)),
                ('face_verified', models.BooleanField(default=False)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='doctor_checkout_photos/')),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_geo_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out')], default='CHECKED_IN', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='healthcenter.doctor')),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_check_ins', to='healthcenter.healthcenter')),
            ],
            options={
                'verbose_name': 'Doctor Check-In',
                'verbose_name_plural': 'Doctor Check-Ins',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
