# Generated by Django 4.2.16 on 2026-05-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0019_doctorcheckin_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcheckin',
            name='checkout_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
