# Generated by Django 4.2.16 on 2026-06-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0020_doctorcheckin_checkout_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcenter.doctor'),
        ),
    ]
