# Generated by Django 4.2.16 on 2026-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0021_patienttreatment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Medicine Unit',
                'verbose_name_plural': 'Medicine Units',
                'ordering': ['unit_name'],
            },
        ),
    ]
