# Generated by Django 4.2.16 on 2026-07-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0023_medicine_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='doctor_prescription_image',
            field=models.ImageField(blank=True, help_text="Doctor's prescription image/file", null=True, upload_to='doctor_prescriptions/'),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='doctor_remarks',
            field=models.TextField(blank=True, help_text="Doctor's remarks/notes", null=True),
        ),
    ]
